from pathlib import Path

p = Path('/Users/fortune/mutx-worktrees/factory/live-main/app/page.tsx')
s = p.read_text()
repls = {
"const navLinks = [\n  { label: 'Manifesto', href: '#manifesto' },\n  { label: 'Systems', href: '#systems' },\n  { label: 'Playbook', href: '#playbook' },\n  { label: 'FAQ', href: '#faq' },\n  { label: 'Docs', href: DOCS_URL, external: true },\n]\n": "const navLinks = [\n  { label: 'Thesis', href: '#manifesto' },\n  { label: 'Control Surface', href: '#systems' },\n  { label: 'Proof', href: '#playbook' },\n  { label: 'FAQ', href: '#faq' },\n  { label: 'Docs', href: DOCS_URL, external: true },\n]\n",
"const heroSignals = [\n  { value: '42ms', label: 'Median policy-gate evaluation' },\n  { value: '99.97%', label: 'Mission continuity with live failover' },\n  { value: '7', label: 'Runtime checkpoints per critical workflow' },\n  { value: '0', label: 'Undocumented operator overrides' },\n]\n": "const heroSignals = [\n  { value: 'API', label: 'Contract-first control plane' },\n  { value: 'CLI', label: 'Operator automation surface' },\n  { value: 'SDK', label: 'Programmatic runtime access' },\n  { value: 'App', label: 'Canonical dashboard for governed operations' },\n]\n",
"const systemCards = [\n  {\n    title: 'Mission Fabric',\n    subtitle: 'Structured execution graph for every autonomous workflow',\n    points: [\n      'Branch-aware state machines for non-linear agent decisions',\n      'Operator snapshots attached to every high-risk transition',\n      'Mission lineage from intent intake to external side effect',\n    ],\n    icon: Layers,\n    gradient: 'from-cyan-400/20 via-sky-400/15 to-blue-500/10',\n  },\n  {\n    title: 'Policy Kernel',\n    subtitle: 'Hard gates that evaluate intent before actions run',\n    points: [\n      'Contextual guardrails for tool scope, spend, and identity',\n      'Pre-execution denial logic with explainable decision traces',\n      'Runtime contracts for compliance-critical workflows',\n    ],\n    icon: Lock,\n    gradient: 'from-fuchsia-400/20 via-violet-400/15 to-indigo-500/10',\n  },\n  {\n    title: 'Ops Relay',\n    subtitle: 'Escalation engine built for real incident response',\n    points: [\n      'SLA-bound routing to the right operator in seconds',\n      'One-click replay from deterministic checkpoints',\n      'Intervention templates for predictable crisis handling',\n    ],\n    icon: Command,\n    gradient: 'from-emerald-400/20 via-teal-400/15 to-cyan-500/10',\n  },\n]\n": "const systemCards = [\n  {\n    title: 'Lifecycle control',\n    subtitle: 'Agents and deployments as first-class resources',\n    points: [\n      'Track agents, deployments, versions, and event history with explicit state',\n      'Operate rollbacks, restarts, and readiness flows from one control layer',\n      'Keep lifecycle semantics consistent across API, CLI, SDK, and app surfaces',\n    ],\n    icon: Layers,\n    gradient: 'from-cyan-400/20 via-sky-400/15 to-blue-500/10',\n  },\n  {\n    title: 'Governance rails',\n    subtitle: 'Ownership, keys, and policy as product behavior',\n    points: [\n      'Enforce ownership boundaries instead of relying on dashboard convention',\n      'Rotate, revoke, and audit API credentials with durable control-plane semantics',\n      'Treat webhooks and approval paths as governed contracts, not side notes',\n    ],\n    icon: Lock,\n    gradient: 'from-fuchsia-400/20 via-violet-400/15 to-indigo-500/10',\n  },\n  {\n    title: 'Operator execution',\n    subtitle: 'One surface for deploy, observe, govern, and recover',\n    points: [\n      'Use the canonical dashboard without splitting product truth across duplicate shells',\n      'Move from runs and traces into concrete operational action',\n      'Bring OpenClaw runtimes under MUTX governance without collapsing into session-only UX',\n    ],\n    icon: Command,\n    gradient: 'from-emerald-400/20 via-teal-400/15 to-cyan-500/10',\n  },\n]\n",
"const playbook = [\n  {\n    stage: '01',\n    title: 'Define the blast radius',\n    body: 'Model missions by risk class. Attach cost ceilings, privileged operation flags, and approval requirements before enabling autonomy.',\n  },\n  {\n    stage: '02',\n    title: 'Launch with telemetry as default',\n    body: 'Every call, handoff, and tool invocation emits structured telemetry so your team can detect drift and latency anomalies early.',\n  },\n  {\n    stage: '03',\n    title: 'Escalate with full context',\n    body: 'When risk thresholds breach, operators get timeline + payload + policy deltas in one view instead of stitching logs across tools.',\n  },\n  {\n    stage: '04',\n    title: 'Recover, replay, improve',\n    body: 'Use checkpoints to restore safely, replay exact conditions, and convert incidents into hardened runbooks for future missions.',\n  },\n]\n": "const playbook = [\n  {\n    stage: '01',\n    title: 'Model the owned resources',\n    body: 'Start with agents, deployments, runs, traces, keys, and webhooks as explicit resources instead of burying operations inside chat transcripts.',\n  },\n  {\n    stage: '02',\n    title: 'Choose the runtime path',\n    body: 'Create a new OpenClaw-backed deployment or link an existing workspace under MUTX governance without changing the product category.',\n  },\n  {\n    stage: '03',\n    title: 'Operate through one control plane',\n    body: 'Keep app, CLI, SDK, and API aligned so the operator surface reflects the same lifecycle and governance contracts everywhere.',\n  },\n  {\n    stage: '04',\n    title: 'Recover with explicit signals',\n    body: 'Use health, readiness, event history, and rollout controls to fix real runtime problems instead of watching a passive session dashboard.',\n  },\n]\n",
"const faqItems = [\n  {\n    q: 'What does “advanced web hacks” translate to here?',\n    a: 'Deliberate visual engineering: layered lighting, kinetic micro-interactions, animated telemetry rails, and highly scannable information architecture that still performs on mobile.',\n  },\n  {\n    q: 'Can we adapt this for enterprise buyers and technical evaluators?',\n    a: 'Yes. The page is structured to support multiple reading paths: executive narrative, systems-level detail, and implementation-oriented trust signals.',\n  },\n  {\n    q: 'Does this replace our current agent framework?',\n    a: 'No. MUTX acts as a control plane around your existing orchestration stack, adding policy gates, runtime observability, and operator response workflows.',\n  },\n  {\n    q: 'How do we avoid fluffy marketing copy over time?',\n    a: 'Anchor copy to outcomes, mechanisms, and constraints. Every section here ties value claims to concrete operating behavior and verifiable control points.',\n  },\n]\n": "const faqItems = [\n  {\n    q: 'Is MUTX just another agent dashboard?',\n    a: 'No. Dashboards observe what happened. MUTX controls what is deployed, who owns it, how credentials are governed, and how the system recovers.',\n  },\n  {\n    q: 'Do I need to replace my runtime to use it?',\n    a: 'No. MUTX can create a new OpenClaw-backed deployment or link an existing workspace under the same control-plane semantics.',\n  },\n  {\n    q: 'What makes the product surface truthful?',\n    a: 'The app shell, API, CLI, and SDK are meant to track the same resource model: agents, deployments, runs, traces, API keys, and webhooks.',\n  },\n  {\n    q: 'Why keep emphasizing governance?',\n    a: 'Because production trust comes from explicit ownership, key lifecycle, webhook contracts, health signals, and recovery loops—not from prettier logs.',\n  },\n]\n",
"const tickerItems = [\n  'Policy-aware autonomy',\n  'Deterministic replay',\n  'Operator-first escalation',\n  'Runtime mission graph',\n  'Identity-bound controls',\n  'Audit-grade telemetry',\n]\n": "const tickerItems = [\n  'Agents get deployments',\n  'Dashboards observe; control planes decide',\n  'Operational trust is the product',\n  'Govern lifecycle, not just sessions',\n  'API + CLI + SDK + app alignment',\n  'OpenClaw compatibility without product drift',\n]\n",
"const missionRail = [\n  {\n    step: 'INTAKE',\n    text: 'User intent classified as “high-impact external action”.',\n    icon: Binary,\n  },\n  {\n    step: 'POLICY',\n    text: 'Kernel validates identity scope + spend cap + approval policy.',\n    icon: Shield,\n  },\n  {\n    step: 'EXECUTION',\n    text: 'Mission branch executes with continuous telemetry stream.',\n    icon: Rocket,\n  },\n  {\n    step: 'REVIEW',\n    text: 'Operator confirms summary diff before side effects commit.',\n    icon: Zap,\n  },\n]\n": "const missionRail = [\n  {\n    step: 'DEPLOY',\n    text: 'Create or link a runtime under MUTX lifecycle semantics.',\n    icon: Binary,\n  },\n  {\n    step: 'GOVERN',\n    text: 'Apply ownership, credentials, and policy boundaries before writes land.',\n    icon: Shield,\n  },\n  {\n    step: 'OBSERVE',\n    text: 'Stream runs, traces, and health signals through the canonical dashboard.',\n    icon: Rocket,\n  },\n  {\n    step: 'RECOVER',\n    text: 'Restart, roll back, or intervene with explicit runtime context.',\n    icon: Zap,\n  },\n]\n",
"const terminalFrames = [\n  '[policy-kernel] evaluating mission_id=mx-4912 risk=high-impact',\n  '[relay] escalation path set → on-call: secops-l2 (SLA 90s)',\n  '[fabric] checkpoint written sha=991af3d replay=true signed=true',\n  '[operator] approval received by @jade · branch merge unlocked',\n]\n": "const terminalFrames = [\n  '[mutx.api] GET /deployments → 200 ok · ownership scope applied',\n  '[mutx.health] readiness=green · webhooks=healthy · auth=online',\n  '[mutx.events] deployment restarted · version=2026.03.19 · actor=operator',\n  '[mutx.keys] rotate complete · previous secret revoked · audit trail written',\n]\n",
"const dashboardStats = [\n  { label: 'Active missions', value: '128', delta: '+18 today' },\n  { label: 'Policy pass rate', value: '99.97%', delta: 'steady' },\n  { label: 'Escalations under SLA', value: '98.8%', delta: '-4s avg' },\n]\n": "const dashboardStats = [\n  { label: 'Primary resources', value: '6', delta: 'agents → webhooks' },\n  { label: 'Operator surfaces', value: '4', delta: 'API · CLI · SDK · App' },\n  { label: 'Runtime paths', value: '2', delta: 'deploy new or link existing' },\n]\n",
"      'approval:',\n      '  requires_human: true',\n      '  max_spend_usd: 2500',\n      '  privileged_tools: [wire_transfer, prod_write]',\n": "      'approval:',\n      '  requires_human: true',\n      '  ownership_scope: team',\n      '  privileged_actions: [deploy_restart, key_rotate]',\n",
"      'await mutx.mission.start({',\n      \"  riskClass: 'high-impact',\",\n      \"  replay: 'deterministic',\",\n      \"  escalation: 'operator-first'\",\n      '})',\n": "      'await mutx.deployments.restart({',\n      \"  deploymentId: 'dep_123',\",\n      \"  reason: 'recover unhealthy replica',\",\n      \"  actor: 'operator'\",\n      '})',\n",
"              Engineered for operators, not pitch decks\n": "              Control plane, not session dashboard\n",
"              Autonomous throughput.\n              <span className=\"block bg-gradient-to-r from-cyan-300 via-sky-200 to-violet-300 bg-clip-text text-transparent\">\n                Human command authority.\n              </span>\n": "              Deploy agents like services.\n              <span className=\"block bg-gradient-to-r from-cyan-300 via-sky-200 to-violet-300 bg-clip-text text-transparent\">\n                Operate them like systems.\n              </span>\n",
"              MUTX is the mission control layer for production AI systems: policy-gated execution, live telemetry, and escalation paths that keep people in charge when the stakes rise.\n": "              MUTX is the open-source control plane for AI agents. It gives teams lifecycle, governance, and operator workflows instead of another session-only dashboard.\n",
"              <p className=\"text-[11px] uppercase tracking-[0.24em] text-white/55\">Live mission rail</p>\n": "              <p className=\"text-[11px] uppercase tracking-[0.24em] text-white/55\">Control loop</p>\n",
"                  <p className=\"font-semibold text-cyan-100\">Mission status: nominal · risk envelope maintained</p>\n                  <p className=\"mt-1 text-white/75\">Pre-exec policy enforcement active · SLA-safe escalation channel online · replay snapshots synced.</p>\n": "                  <p className=\"font-semibold text-cyan-100\">Control-plane status: healthy · governance rails online</p>\n                  <p className=\"mt-1 text-white/75\">Lifecycle controls active · ownership enforced · health and readiness signals flowing into the dashboard.</p>\n",
"                  <p className=\"mb-3 text-[11px] uppercase tracking-[0.2em] text-white/50\">Animated terminal TUI</p>\n": "                  <p className=\"mb-3 text-[11px] uppercase tracking-[0.2em] text-white/50\">Runtime events</p>\n",
"                  <p className=\"mb-3 text-[11px] uppercase tracking-[0.2em] text-white/50\">Dashboard snapshot</p>\n": "                  <p className=\"mb-3 text-[11px] uppercase tracking-[0.2em] text-white/50\">Product surface snapshot</p>\n",
"                      <span>Policy decisions (24h)</span>\n                      <span>12,881 evals</span>\n": "                      <span>Canonical scope</span>\n                      <span>deploy · observe · govern</span>\n",
"            <p className=\"text-xs uppercase tracking-[0.24em] text-white/55\">Manifesto</p>\n": "            <p className=\"text-xs uppercase tracking-[0.24em] text-white/55\">Category thesis</p>\n",
"              AI systems shouldn&apos;t be trusted because they sound smart. They should be trusted because they are governable under stress.\n": "              The hard part is not the model. It is everything after the demo: ownership, deployment semantics, recovery paths, and operational trust.\n",
"            <p className=\"text-xs uppercase tracking-[0.24em] text-white/55\">Core systems</p>\n            <h2 className=\"mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl\">The stack behind safe autonomous execution.</h2>\n": "            <p className=\"text-xs uppercase tracking-[0.24em] text-white/55\">What MUTX actually controls</p>\n            <h2 className=\"mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl\">Lifecycle, governance, and operator execution in one control layer.</h2>\n",
"            <p className=\"text-xs uppercase tracking-[0.24em] text-white/55\">Deployment playbook</p>\n            <h2 className=\"mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl\">How teams operationalize MUTX in the real world.</h2>\n": "            <p className=\"text-xs uppercase tracking-[0.24em] text-white/55\">Proof</p>\n            <h2 className=\"mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl\">Where dashboards stop, MUTX starts.</h2>\n",
"          <p className=\"text-xs font-semibold uppercase tracking-[0.24em] text-cyan-100/80\">Build a better control surface</p>\n          <h2 className=\"mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl\">Ship high-agency AI without surrendering operational control.</h2>\n          <p className=\"mx-auto mt-3 max-w-3xl text-sm leading-7 text-white/80 sm:text-base\">\n            If your team is done with vague platform promises and wants concrete runtime control, open the docs and run your first guarded mission today.\n          </p>\n": "          <p className=\"text-xs font-semibold uppercase tracking-[0.24em] text-cyan-100/80\">Operate your agents like production systems</p>\n          <h2 className=\"mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl\">Move from demo agent to governed deployment.</h2>\n          <p className=\"mx-auto mt-3 max-w-3xl text-sm leading-7 text-white/80 sm:text-base\">\n            If your agents need to survive beyond a demo, start with MUTX: explicit resources, truthful health signals, and one control plane across app, API, CLI, and SDK.\n          </p>\n",
"              Open docs\n": "              Launch docs\n",
"              View repository\n": "              View source\n",
}
for old, new in repls.items():
    if old not in s:
        raise SystemExit(f'Missing expected block:\n{old[:140]}')
    s = s.replace(old, new)
p.write_text(s)
