# Auto-generated by subagent for test coverage task
import pytest
from uuid import uuid4
from unittest.mock import Mock, AsyncMock, patch
import httpx
import importlib.util


# Import ClawHub and Skill directly from the worktree file to avoid the
# sdk/mutx/__init__.py chain which would pull in the wrong mutx namespace.
def _load_clawhub():
    spec = importlib.util.spec_from_file_location(
        "clawhub",
        "/Users/fortune/mutx-worktrees/factory/backend/sdk/mutx/clawhub.py",
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_clawhub = _load_clawhub()
ClawHub = _clawhub.ClawHub
Skill = _clawhub.Skill


# ---------------------------------------------------------------------------
# Skill unit tests
# ---------------------------------------------------------------------------


class TestSkill:
    """Tests for the Skill dataclass."""

    def test_skill_creates_all_fields(self):
        data = {
            "id": "skill-1",
            "name": "my-skill",
            "description": "A test skill",
            "author": "tester",
            "stars": 42,
            "category": "productivity",
            "is_official": True,
        }
        skill = Skill(data)

        assert skill.id == "skill-1"
        assert skill.name == "my-skill"
        assert skill.description == "A test skill"
        assert skill.author == "tester"
        assert skill.stars == 42
        assert skill.category == "productivity"
        assert skill.is_official is True
        assert skill._data == data

    def test_skill_defaults_is_official_false(self):
        data = {
            "id": "skill-2",
            "name": "unofficial-skill",
            "description": "Not official",
            "author": "tester",
            "stars": 0,
            "category": "misc",
        }
        skill = Skill(data)

        assert skill.is_official is False

    def test_skill_repr(self):
        data = {
            "id": "skill-3",
            "name": "repr-skill",
            "description": "Repr test",
            "author": "alice",
            "stars": 10,
            "category": "test",
        }
        skill = Skill(data)

        assert "skill-3" in repr(skill)
        assert "repr-skill" in repr(skill)
        assert "alice" in repr(skill)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def make_response(status: int, json_data):
    """Build a mock httpx.Response that behaves enough for our tests."""
    response = Mock(spec=httpx.Response)
    response.status_code = status
    response.json = Mock(return_value=json_data)
    response.raise_for_status = Mock()
    if status >= 400:
        response.raise_for_status.side_effect = httpx.HTTPStatusError(
            "error", request=Mock(spec=httpx.Request), response=response
        )
    return response


# ---------------------------------------------------------------------------
# ClawHub sync tests
# ---------------------------------------------------------------------------


class TestClawHubSyncListSkills:
    """Tests for ClawHub.list_skills (sync)."""

    def test_list_skills_returns_skill_objects(self):
        skills_data = [
            {
                "id": "s1",
                "name": "Skill One",
                "description": "First skill",
                "author": "alice",
                "stars": 5,
                "category": "ai",
            },
            {
                "id": "s2",
                "name": "Skill Two",
                "description": "Second skill",
                "author": "bob",
                "stars": 10,
                "category": "tools",
                "is_official": True,
            },
        ]

        mock_client = Mock(spec=httpx.Client)
        mock_client.get.return_value = make_response(200, skills_data)
        hub = ClawHub(mock_client)

        skills = hub.list_skills()

        assert len(skills) == 2
        assert all(isinstance(s, Skill) for s in skills)
        assert skills[0].name == "Skill One"
        assert skills[1].is_official is True
        mock_client.get.assert_called_once_with("/v1/clawhub/skills")

    def test_list_skills_raises_on_async_client(self):
        mock_client = Mock(spec=httpx.AsyncClient)
        hub = ClawHub(mock_client)

        with pytest.raises(RuntimeError, match="Use alist_skills"):
            hub.list_skills()

    def test_list_skills_raises_on_http_error(self):
        mock_client = Mock(spec=httpx.Client)
        mock_client.get.return_value = make_response(500, {"error": "server error"})
        hub = ClawHub(mock_client)

        with pytest.raises(httpx.HTTPStatusError):
            hub.list_skills()


class TestClawHubSyncInstallSkill:
    """Tests for ClawHub.install_skill (sync)."""

    def test_install_skill_returns_response(self):
        response_data = {"status": "installed", "agent_id": "a1", "skill_id": "s1"}

        mock_client = Mock(spec=httpx.Client)
        mock_client.post.return_value = make_response(200, response_data)
        hub = ClawHub(mock_client)

        result = hub.install_skill(agent_id="a1", skill_id="s1")

        assert result == response_data
        mock_client.post.assert_called_once_with(
            "/v1/clawhub/install", json={"agent_id": "a1", "skill_id": "s1"}
        )

    def test_install_skill_accepts_uuid(self):
        response_data = {"status": "installed"}

        mock_client = Mock(spec=httpx.Client)
        mock_client.post.return_value = make_response(200, response_data)
        hub = ClawHub(mock_client)

        agent_uuid = uuid4()
        hub.install_skill(agent_id=agent_uuid, skill_id="s1")

        mock_client.post.assert_called_once_with(
            "/v1/clawhub/install", json={"agent_id": str(agent_uuid), "skill_id": "s1"}
        )

    def test_install_skill_raises_on_async_client(self):
        mock_client = Mock(spec=httpx.AsyncClient)
        hub = ClawHub(mock_client)

        with pytest.raises(RuntimeError, match="Use ainstall_skill"):
            hub.install_skill(agent_id="a1", skill_id="s1")

    def test_install_skill_raises_on_http_error(self):
        mock_client = Mock(spec=httpx.Client)
        mock_client.post.return_value = make_response(400, {"error": "bad request"})
        hub = ClawHub(mock_client)

        with pytest.raises(httpx.HTTPStatusError):
            hub.install_skill(agent_id="a1", skill_id="s1")


class TestClawHubSyncUninstallSkill:
    """Tests for ClawHub.uninstall_skill (sync)."""

    def test_uninstall_skill_returns_response(self):
        response_data = {"status": "uninstalled", "agent_id": "a1", "skill_id": "s1"}

        mock_client = Mock(spec=httpx.Client)
        mock_client.post.return_value = make_response(200, response_data)
        hub = ClawHub(mock_client)

        result = hub.uninstall_skill(agent_id="a1", skill_id="s1")

        assert result == response_data
        mock_client.post.assert_called_once_with(
            "/v1/clawhub/uninstall", json={"agent_id": "a1", "skill_id": "s1"}
        )

    def test_uninstall_skill_raises_on_async_client(self):
        mock_client = Mock(spec=httpx.AsyncClient)
        hub = ClawHub(mock_client)

        with pytest.raises(RuntimeError, match="Use auninstall_skill"):
            hub.uninstall_skill(agent_id="a1", skill_id="s1")

    def test_uninstall_skill_raises_on_http_error(self):
        mock_client = Mock(spec=httpx.Client)
        mock_client.post.return_value = make_response(404, {"error": "not found"})
        hub = ClawHub(mock_client)

        with pytest.raises(httpx.HTTPStatusError):
            hub.uninstall_skill(agent_id="a1", skill_id="s1")


# ---------------------------------------------------------------------------
# ClawHub async tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
class TestClawHubAsyncListSkills:
    """Tests for ClawHub.alist_skills (async)."""

    async def test_alist_skills_returns_skill_objects(self):
        skills_data = [
            {
                "id": "s1",
                "name": "Async Skill",
                "description": "An async skill",
                "author": "bob",
                "stars": 7,
                "category": "async_tools",
            },
        ]

        # httpx Response methods are synchronous; await is only on client.get()
        mock_response = Mock(spec=httpx.Response)
        mock_response.status_code = 200
        mock_response.json = Mock(return_value=skills_data)
        mock_response.raise_for_status = Mock()

        mock_client = AsyncMock(spec=httpx.AsyncClient)
        mock_client.get.return_value = mock_response
        hub = ClawHub(mock_client)

        skills = await hub.alist_skills()

        assert len(skills) == 1
        assert isinstance(skills[0], Skill)
        assert skills[0].name == "Async Skill"
        mock_client.get.assert_called_once_with("/v1/clawhub/skills")

    async def test_alist_skills_raises_on_sync_client(self):
        mock_client = Mock(spec=httpx.Client)
        hub = ClawHub(mock_client)

        with pytest.raises(RuntimeError, match="Use list_skills"):
            await hub.alist_skills()

    async def test_alist_skills_raises_on_http_error(self):
        # httpx Response.raise_for_status() is synchronous
        mock_response = Mock(spec=httpx.Response)
        mock_response.status_code = 500
        mock_response.json = Mock(return_value={"error": "server error"})
        mock_response.raise_for_status = Mock(
            side_effect=httpx.HTTPStatusError(
                "error", request=Mock(spec=httpx.Request), response=mock_response
            )
        )

        mock_client = AsyncMock(spec=httpx.AsyncClient)
        mock_client.get.return_value = mock_response
        hub = ClawHub(mock_client)

        with pytest.raises(httpx.HTTPStatusError):
            await hub.alist_skills()


@pytest.mark.asyncio
class TestClawHubAsyncInstallSkill:
    """Tests for ClawHub.ainstall_skill (async)."""

    async def test_ainstall_skill_returns_response(self):
        response_data = {"status": "installed", "agent_id": "a1", "skill_id": "s1"}

        mock_response = Mock(spec=httpx.Response)
        mock_response.status_code = 200
        mock_response.json = Mock(return_value=response_data)
        mock_response.raise_for_status = Mock()

        mock_client = AsyncMock(spec=httpx.AsyncClient)
        mock_client.post.return_value = mock_response
        hub = ClawHub(mock_client)

        result = await hub.ainstall_skill(agent_id="a1", skill_id="s1")

        assert result == response_data
        mock_client.post.assert_called_once_with(
            "/v1/clawhub/install", json={"agent_id": "a1", "skill_id": "s1"}
        )

    async def test_ainstall_skill_accepts_uuid(self):
        response_data = {"status": "installed"}

        mock_response = Mock(spec=httpx.Response)
        mock_response.status_code = 200
        mock_response.json = Mock(return_value=response_data)
        mock_response.raise_for_status = Mock()

        mock_client = AsyncMock(spec=httpx.AsyncClient)
        mock_client.post.return_value = mock_response
        hub = ClawHub(mock_client)

        agent_uuid = uuid4()
        await hub.ainstall_skill(agent_id=agent_uuid, skill_id="s1")

        mock_client.post.assert_called_once_with(
            "/v1/clawhub/install", json={"agent_id": str(agent_uuid), "skill_id": "s1"}
        )

    async def test_ainstall_skill_raises_on_sync_client(self):
        mock_client = Mock(spec=httpx.Client)
        hub = ClawHub(mock_client)

        with pytest.raises(RuntimeError, match="Use install_skill"):
            await hub.ainstall_skill(agent_id="a1", skill_id="s1")


@pytest.mark.asyncio
class TestClawHubAsyncUninstallSkill:
    """Tests for ClawHub.auninstall_skill (async)."""

    async def test_auninstall_skill_returns_response(self):
        response_data = {"status": "uninstalled"}

        mock_response = Mock(spec=httpx.Response)
        mock_response.status_code = 200
        mock_response.json = Mock(return_value=response_data)
        mock_response.raise_for_status = Mock()

        mock_client = AsyncMock(spec=httpx.AsyncClient)
        mock_client.post.return_value = mock_response
        hub = ClawHub(mock_client)

        result = await hub.auninstall_skill(agent_id="a1", skill_id="s1")

        assert result == response_data
        mock_client.post.assert_called_once_with(
            "/v1/clawhub/uninstall", json={"agent_id": "a1", "skill_id": "s1"}
        )

    async def test_auninstall_skill_raises_on_sync_client(self):
        mock_client = Mock(spec=httpx.Client)
        hub = ClawHub(mock_client)

        with pytest.raises(RuntimeError, match="Use uninstall_skill"):
            await hub.auninstall_skill(agent_id="a1", skill_id="s1")

    async def test_auninstall_skill_raises_on_http_error(self):
        mock_response = Mock(spec=httpx.Response)
        mock_response.status_code = 404
        mock_response.json = Mock(return_value={"error": "not found"})
        mock_response.raise_for_status = Mock(
            side_effect=httpx.HTTPStatusError(
                "error", request=Mock(spec=httpx.Request), response=mock_response
            )
        )

        mock_client = AsyncMock(spec=httpx.AsyncClient)
        mock_client.post.return_value = mock_response
        hub = ClawHub(mock_client)

        with pytest.raises(httpx.HTTPStatusError):
            await hub.auninstall_skill(agent_id="a1", skill_id="s1")
