// Generated by scripts/build-pico-content.mjs. Do not edit by hand.

export const PICO_GENERATED_CONTENT = {
  "generatedAt": "2026-07-16T08:40:35.694Z",
  "packSnapshot": {
    "generatedAt": "2026-07-16T08:40:34.052Z",
    "generatedOn": "2026-07-16",
    "refreshedAt": "2026-07-16",
    "docCount": 19,
    "visibleDocCount": 17,
    "lessonCount": 12,
    "totalLessonMinutes": 274,
    "sourcePaths": [
      "/private/tmp/mutx-pico-upstreams/src/api/knowledge/pico-builder-pack"
    ],
    "currentProductNotes": [
      "Hermes now has official Termux docs, a local dashboard, an OpenAI-compatible API server, and six terminal backends.",
      "OpenClaw now recommends Node 24, uses stricter config validation, and has clearer auth-profile and Tailscale dashboard flows.",
      "NanoClaw v2 now uses the shell-driven `nanoclaw.sh` bootstrap with OneCLI, Docker, and Claude Code.",
      "PicoClaw now has config schema v2, `.security.yml`, Android APK install, a mature launcher/TUI split, and official Docker Compose flows."
    ]
  },
  "stacks": [
    {
      "id": "hermes",
      "name": "Hermes",
      "productProfile": "Hermes is the default recommendation in this pack when the user wants a persistent agent that improves over time rather than acting like a fresh stateless assistant each session.",
      "strengths": [
        "built-in learning loop",
        "persistent sessions and cross-session recall",
        "strong CLI plus gateway-oriented workflow",
        "dashboard and API server options",
        "profiles for isolated instances",
        "cron / scheduled automation support",
        "multiple terminal backends",
        "good diagnostics and state export"
      ],
      "fitSignals": [
        "“I want the best general personal agent.”",
        "“I want something that gets better over time.”",
        "“I want one always-on agent hub.”",
        "“I want memory, sessions, and skills.”",
        "“I want it on a VPS or always-on mini PC.”"
      ],
      "installRealities": [
        "the current audited release tag is v2026.7.7.2 (package 0.18.2) and requires Python >=3.11,<3.14",
        "the official fast path is the one-line install script documented on the Hermes docs site",
        "Linux, macOS, WSL2, and Android via Termux are supported paths in current docs",
        "native Windows is not the primary path; use WSL2 instead",
        "the dashboard binds to `127.0.0.1:9119` and has no built-in auth",
        "the API server exposes Hermes as an OpenAI-compatible endpoint on `127.0.0.1:8642` when enabled",
        "six terminal backends are documented: local, Docker, SSH, Daytona, Singularity, Modal",
        "`AGENTS.md` is a first-class context file and is loaded automatically",
        "the local backend is not a sandbox; for untrusted code, recommend Docker or another isolated backend"
      ],
      "troubleshootingThemes": [
        "provider config mismatch",
        "local backend used when the user expected container isolation",
        "dashboard exposed beyond localhost without realizing it has no auth",
        "wrong profile / wrong `HERMES_HOME`",
        "missing optional tool dependencies from the manual install path",
        "config drift after updates",
        "remote access set up before local success was verified"
      ],
      "officialSources": [
        "https://github.com/NousResearch/hermes-agent",
        "https://github.com/NousResearch/hermes-agent/releases",
        "https://hermes-agent.nousresearch.com/docs/getting-started/installation",
        "https://hermes-agent.nousresearch.com/docs/getting-started/termux",
        "https://hermes-agent.nousresearch.com/docs/reference/cli-commands",
        "https://hermes-agent.nousresearch.com/docs/user-guide/features/web-dashboard",
        "https://hermes-agent.nousresearch.com/docs/user-guide/features/api-server",
        "https://hermes-agent.nousresearch.com/docs/user-guide/configuration",
        "https://hermes-agent.nousresearch.com/docs/user-guide/features/context-files"
      ],
      "repoUrl": "https://github.com/NousResearch/hermes-agent",
      "docsUrl": "https://hermes-agent.nousresearch.com/docs/getting-started/installation",
      "live": {
        "stars": 215665,
        "openIssues": 23016,
        "pushedAt": "2026-07-16T08:31:30Z",
        "repoUrl": "https://github.com/NousResearch/hermes-agent",
        "latestRef": {
          "kind": "release",
          "label": "Release v2026.7.7.2",
          "title": "Hermes Agent v0.18.2 (2026.7.7.2)",
          "publishedAt": "2026-07-08T03:11:22Z",
          "url": "https://github.com/NousResearch/hermes-agent/releases/tag/v2026.7.7.2"
        }
      }
    },
    {
      "id": "openclaw",
      "name": "OpenClaw",
      "productProfile": "OpenClaw is the right recommendation when the user wants a broad multi-channel ecosystem, strong gateway workflow, multi-agent routing, companion surfaces, and a visual Control UI.",
      "strengths": [
        "local-first gateway control plane",
        "wide messaging and channel support",
        "multi-agent routing",
        "browser-based Control UI",
        "onboarding-driven setup with daemon install",
        "auth profiles and multiple provider paths",
        "plugin / tool / skill layering",
        "Tailscale integration for private remote dashboard access"
      ],
      "fitSignals": [
        "“I want the most integrations.”",
        "“I want companion apps and messaging surfaces.”",
        "“I want multiple channels and multiple agents.”",
        "“I want a visual dashboard.”",
        "“I want broad ecosystem reach.”"
      ],
      "installRealities": [
        "release 2026.7.1 supports Node 22.22.3+, 24.15+, or 25.9+; Node 24.15+ is the recommended baseline",
        "the current happy path is install first, then `openclaw onboard --install-daemon`",
        "the current docs verify success with `openclaw gateway status` and then `openclaw dashboard`",
        "the local Control UI is at `http://127.0.0.1:18789/`",
        "the main config path is `~/.openclaw/openclaw.json`",
        "config validation is strict; unknown keys or invalid values can prevent the Gateway from starting",
        "`openclaw config schema` prints the live JSON schema and is the best machine-readable truth",
        "auth is per-agent via `auth-profiles.json`, not one giant global auth blob",
        "OpenClaw can auto-configure Tailscale Serve or Funnel while keeping the Gateway on loopback",
        "binding beyond loopback without auth is blocked",
        "pairing codes expire after 1 hour by default in pairing mode"
      ],
      "troubleshootingThemes": [
        "Node runtime mismatch",
        "invalid config or legacy keys",
        "gateway not running",
        "auth mode mismatch between gateway and Control UI",
        "onboarding incomplete",
        "channel auth incomplete",
        "pairing not approved yet",
        "local model endpoint config issues",
        "Tailscale Serve/Funnel confusion"
      ],
      "officialSources": [
        "https://github.com/openclaw/openclaw",
        "https://docs.openclaw.ai/",
        "https://docs.openclaw.ai/start/getting-started",
        "https://docs.openclaw.ai/start/wizard",
        "https://docs.openclaw.ai/install/node",
        "https://docs.openclaw.ai/gateway/configuration",
        "https://docs.openclaw.ai/gateway/configuration-reference",
        "https://docs.openclaw.ai/web/control-ui",
        "https://docs.openclaw.ai/gateway/tailscale",
        "https://docs.openclaw.ai/help/faq",
        "https://docs.openclaw.ai/channels/telegram",
        "https://docs.openclaw.ai/gateway/security",
        "https://docs.openclaw.ai/concepts/model-providers",
        "https://docs.openclaw.ai/concepts/oauth"
      ],
      "repoUrl": "https://github.com/openclaw/openclaw",
      "docsUrl": "https://docs.openclaw.ai/",
      "live": {
        "stars": 383089,
        "openIssues": 6736,
        "pushedAt": "2026-07-16T08:39:01Z",
        "repoUrl": "https://github.com/openclaw/openclaw",
        "latestRef": {
          "kind": "release",
          "label": "Release v2026.7.1",
          "title": "openclaw 2026.7.1",
          "publishedAt": "2026-07-13T22:33:14Z",
          "url": "https://github.com/openclaw/openclaw/releases/tag/v2026.7.1"
        }
      }
    },
    {
      "id": "nanoclaw",
      "name": "NanoClaw",
      "productProfile": "NanoClaw is the recommendation for users who want a smaller, easier-to-audit codebase and stronger isolation via containers rather than a giant all-in-one surface.",
      "strengths": [
        "lightweight mental model",
        "container isolation for agent runtime",
        "easier to understand and customize",
        "security-oriented positioning",
        "deterministic v2 setup path via `bash nanoclaw.sh`",
        "fork-first customization model",
        "skills over feature bloat"
      ],
      "fitSignals": [
        "“I don’t want to trust a huge codebase with my whole machine.”",
        "“I want agents isolated in containers.”",
        "“I want something smaller and easier to reason about.”",
        "“I’m okay with a more builder-oriented workflow.”"
      ],
      "installRealities": [
        "the current v2 quick start is clone, `cd` into the repo, then run `bash nanoclaw.sh` directly in the shell",
        "`nanoclaw.sh` owns the deterministic bootstrap and invokes Claude Code only when judgment is required",
        "Node.js 20+, Docker, Claude Code, and OneCLI are current prerequisites",
        "Docker is the default container runtime and works on macOS/Linux/Windows via WSL2",
        "Apple Container is macOS-only",
        "OneCLI Agent Vault is the modern credential path; current docs pin that shift to v1.2.35+",
        "`nanoclaw.sh` can bootstrap Node, pnpm, Docker, OneCLI, the agent container, and the first channel",
        "WSL users should clone into the Linux filesystem (`~/nanoclaw`), not `/mnt/c/...`",
        "v2 uses the setup script and channel adapters; do not reuse v1 branch-marketplace instructions",
        "diagnostics are opt-in during setup and update flows"
      ],
      "troubleshootingThemes": [
        "Docker missing or misconfigured",
        "Claude Code missing or launched in the wrong directory",
        "`nanoclaw.sh` launched from the wrong checkout or interrupted mid-bootstrap",
        "OneCLI Agent Vault not running or not configured",
        "container/service startup problems",
        "wrong assumption that normal shell commands can replace Claude Code skills",
        "stale v1 customization assumptions after moving to v2",
        "WhatsApp re-merge or auth breakage after release changes"
      ],
      "officialSources": [
        "https://github.com/nanocoai/nanoclaw",
        "https://docs.nanoclaw.dev/",
        "https://docs.nanoclaw.dev/introduction",
        "https://docs.nanoclaw.dev/quickstart",
        "https://docs.nanoclaw.dev/installation",
        "https://docs.nanoclaw.dev/integrations/skills-system",
        "https://docs.nanoclaw.dev/api/skills/creating-skills",
        "https://docs.nanoclaw.dev/api/configuration",
        "https://docs.nanoclaw.dev/advanced/troubleshooting",
        "https://docs.nanoclaw.dev/changelog"
      ],
      "repoUrl": "https://github.com/nanocoai/nanoclaw",
      "docsUrl": "https://docs.nanoclaw.dev/",
      "live": {
        "stars": 30265,
        "openIssues": 844,
        "pushedAt": "2026-07-15T08:22:41Z",
        "repoUrl": "https://github.com/nanocoai/nanoclaw",
        "latestRef": {
          "kind": "release",
          "label": "Release v2.1.17",
          "title": "v2.1.17",
          "publishedAt": "2026-06-17T14:51:14Z",
          "url": "https://github.com/nanocoai/nanoclaw/releases/tag/v2.1.17"
        }
      }
    },
    {
      "id": "picoclaw",
      "name": "PicoClaw",
      "productProfile": "PicoClaw is the recommendation for ultra-lightweight deployment, low-cost hardware, Android, and edge-device use cases where footprint matters more than a huge ecosystem.",
      "strengths": [
        "written in Go",
        "very small resource footprint",
        "launcher / browser-based setup path",
        "TUI launcher for headless environments",
        "model-centric provider configuration",
        "sandboxed workspace defaults",
        "good fit for low-cost hardware and edge scenarios"
      ],
      "fitSignals": [
        "“I want this on tiny hardware.”",
        "“I want the lightest possible agent stack.”",
        "“I want a launcher/web UI setup path.”",
        "“I want edge deployment more than ecosystem breadth.”",
        "“I want Android or embedded-device options.”"
      ],
      "installRealities": [
        "the current audited release is v0.3.1; use its checksums file for downloaded binaries",
        "the official website download is still the recommended fast path",
        "the docs keep the core source install lighter than the full launcher development path",
        "the core docs still show a Go 1.21+ source path, so do not tell users they need the full Go + Node + pnpm stack unless they are actually building launcher/Web UI components",
        "the repo README currently calls for Go 1.25+, Node.js 22+, and pnpm 10.33.0+ for launcher / Web UI development builds",
        "the workspace is `~/.picoclaw/`",
        "config lives at `~/.picoclaw/config.json`",
        "config schema `2` is current",
        "`.security.yml` is a first-class place for secrets",
        "in schema `2`, model credentials should come from `.security.yml`; `config.json` `api_key` can be ignored for `model_list`",
        "the v0.3.1 desktop release archives include both `picoclaw` and `picoclaw-launcher`; generated packages install both into `~/.local/bin`",
        "add `~/.local/bin` to `PATH` before using bare PicoClaw commands in a new shell",
        "the audited v0.3.1 release and source tree do not ship `picoclaw-launcher-tui`; do not recommend that command",
        "adding `-public` to the launcher broadens exposure to all interfaces, so it is not a safe default",
        "Docker and Android are now first-class documented install paths",
        "the gateway handles all enabled channels concurrently",
        "`restrict_to_workspace` defaults to `true`"
      ],
      "troubleshootingThemes": [
        "config version mismatch",
        "provider config errors",
        "secrets stored in the wrong file",
        "launcher reachable locally but not remotely because it is bound only to localhost",
        "macOS Gatekeeper blocking the unsigned launcher on first run",
        "workspace restriction surprises",
        "unsupported or incomplete edge-hardware assumptions",
        "early-development bugs",
        "user trying to disable safety boundaries too early"
      ],
      "officialSources": [
        "https://github.com/sipeed/picoclaw",
        "https://github.com/sipeed/picoclaw/releases",
        "https://picoclaw.io/",
        "https://docs.picoclaw.io/docs/",
        "https://docs.picoclaw.io/docs/getting-started/",
        "https://docs.picoclaw.io/docs/installation/",
        "https://docs.picoclaw.io/docs/installation/android/",
        "https://docs.picoclaw.io/docs/configuration/",
        "https://docs.picoclaw.io/docs/configuration/security-sandbox/",
        "https://docs.picoclaw.io/docs/configuration/config-reference",
        "https://docs.picoclaw.io/docs/channels/",
        "https://docs.picoclaw.io/docs/docker/"
      ],
      "repoUrl": "https://github.com/sipeed/picoclaw",
      "docsUrl": "https://docs.picoclaw.io/docs/",
      "live": {
        "stars": 29763,
        "openIssues": 66,
        "pushedAt": "2026-07-09T17:19:37Z",
        "repoUrl": "https://github.com/sipeed/picoclaw",
        "latestRef": {
          "kind": "release",
          "label": "Release v0.3.1",
          "title": "v0.3.1",
          "publishedAt": "2026-07-03T07:37:06Z",
          "url": "https://github.com/sipeed/picoclaw/releases/tag/v0.3.1"
        }
      }
    }
  ],
  "remoteAccess": {
    "title": "Private-first remote access",
    "why": "For self-hosted agents, Tailscale is usually the safest default because it avoids exposing admin surfaces directly to the public internet.",
    "decisionDefaults": [
      "`tailscale ssh` for shell",
      "`tailscale serve` for private web surfaces",
      "SSH tunnel if the app must stay local and Serve is not appropriate",
      "direct tailnet bind only when the app is meant to listen on a tailnet interface",
      "`tailscale funnel` only for intentional public exposure"
    ],
    "officialSources": [
      "https://tailscale.com/docs/features/magicdns",
      "https://tailscale.com/docs/features/tailscale-serve",
      "https://tailscale.com/docs/features/tailscale-funnel",
      "https://tailscale.com/docs/features/tailscale-ssh",
      "https://tailscale.com/docs/features/tailscale-ssh/tailscale-ssh-console",
      "https://tailscale.com/docs/reference/funnel-vs-sharing",
      "https://tailscale.com/docs/reference/tailscale-cli",
      "https://docs.openclaw.ai/gateway/tailscale"
    ],
    "docsUrl": "https://tailscale.com/docs/features/magicdns"
  },
  "landing": {
    "meta": {
      "title": "PicoMUTX — Real Operator Guidance For Hermes, OpenClaw, NanoClaw, and PicoClaw",
      "description": "PicoMUTX turns 17 builder-pack playbooks, 12 guided lessons, and live repo signals across Hermes, OpenClaw, NanoClaw, and PicoClaw into one safer operator path."
    },
    "nav": {
      "brand": "PicoMUTX",
      "brandTag": " by MUTX",
      "cta": "Pre-register"
    },
    "hero": {
      "badge": "Docs synced 2026-07-16 · 17 live playbooks",
      "title": "Build, deploy, and govern real ",
      "titleAccent": "Hermes, OpenClaw, NanoClaw, and PicoClaw stacks without stale guesswork.",
      "subtitle": "PicoMUTX is grounded in the official install, dashboard, security, and troubleshooting surfaces for Hermes, OpenClaw, NanoClaw, and PicoClaw. It gives founders and operators one guided path instead of another pile of tabs.",
      "cta": "Pre-Register for Early Access",
      "ctaSecondary": "See pricing",
      "meta": "12 guided lessons · about 274 minutes of sequenced work · Tailscale-first remote access defaults"
    },
    "trustItems": [
      "17 builder-pack docs mapped into one product surface",
      "4 tracked stacks with live repo snapshots",
      "Safer launch posture: approval-aware tutoring and private-first remote access"
    ],
    "problem": {
      "eyebrow": "The Actual Friction",
      "title": "The hard part is not wanting an agent.",
      "titleLine2": "It is keeping up with the moving surface area after you pick a stack.",
      "body": "Hermes, OpenClaw, NanoClaw, and PicoClaw each have different install paths, auth models, dashboards, and security traps. The product has to translate that moving reality into one sequence you can actually follow.",
      "scenarios": [
        {
          "label": "\"I do not know which stack fits my job.\"",
          "body": "Pico starts with fit signals, install realities, and tradeoffs instead of pretending every stack is interchangeable."
        },
        {
          "label": "\"The guide I followed is already stale.\"",
          "body": "Repo releases, runtime floors, and auth paths move fast. The platform should track those changes instead of locking copy in amber."
        },
        {
          "label": "\"My runtime works locally, but remote access feels risky.\"",
          "body": "Dashboards and launchers should not become public just because the first path was the fastest path."
        },
        {
          "label": "\"I can install things, but I still do not have an operator loop.\"",
          "body": "A working agent needs lessons, tutoring, support, monitoring, and approval-aware controls that line up with each other."
        }
      ],
      "close": "That is the product lane PicoMUTX is filling in."
    },
    "platform": {
      "eyebrow": "What The Platform Now Knows",
      "title": "One product surface fed by actual stack knowledge.",
      "body": "The app is now being filled from 17 pack docs, 12 structured lessons, and live repo signals. That means the landing, onboarding, tutor, and support surfaces can start telling the truth about what these stacks actually require.",
      "howItWorks": [
        {
          "title": "Compare stacks with current install and security realities",
          "body": "Use live briefs for Hermes, OpenClaw, NanoClaw, and PicoClaw instead of generic “best stack” copy divorced from official docs."
        },
        {
          "title": "Move through a real sequence from local success to control",
          "body": "The Academy already encodes the path from install, to persistence, to skills, to monitoring, to approval gates."
        },
        {
          "title": "Route blockers into evidence-first tutoring and support",
          "body": "Tutor prompts and support lanes now begin from real failure modes pulled from the pack instead of generic motivation copy."
        },
        {
          "title": "Keep remote access private by default",
          "body": "Tailscale stays the default posture for dashboards, launchers, and API surfaces that should not be open to the public internet."
        }
      ]
    },
    "who": {
      "eyebrow": "Who This Fits",
      "title": "PicoMUTX is for operators who need current truth, not hype.",
      "forYouTitle": "This is for you if…",
      "notForYouTitle": "This is not for you if…",
      "forYou": [
        "You need to choose between Hermes, OpenClaw, NanoClaw, or PicoClaw with less wasted motion",
        "You want a guided install-to-operations sequence instead of stitched-together docs",
        "You care about safer remote access and approval-aware control surfaces",
        "You want tutoring and human help tied to the same underlying stack truth",
        "You are willing to produce proof artifacts instead of collecting vague setup feelings"
      ],
      "notForYou": [
        "You want broad AI-agent marketing without touching the real install details",
        "You plan to expose dashboards or launchers publicly before you understand the risk boundary",
        "You already have a mature internal control plane and only need custom enterprise governance",
        "You want a toy demo more than a runtime that survives operations",
        "You expect one frozen tutorial to stay accurate while the repos keep shipping"
      ]
    },
    "beforeAfter": {
      "eyebrow": "What Changes",
      "title": "What changes when the UI is grounded in live stack facts",
      "beforeLabel": "Before",
      "afterLabel": "After",
      "items": [
        {
          "before": "Marketing copy talks about “AI agents” in the abstract",
          "after": "The product names Hermes, OpenClaw, NanoClaw, and PicoClaw explicitly and shows why each one exists"
        },
        {
          "before": "Onboarding is generic even when the lessons are specific",
          "after": "The first moves mirror the actual lesson objectives and proof requirements"
        },
        {
          "before": "Tutor examples are detached from current stack failure modes",
          "after": "Tutor prompts start from real install, dashboard, and launcher breakpoints"
        },
        {
          "before": "A WIP route apologizes for being empty",
          "after": "The route becomes a live build ledger with tracked repos, docs, and remote-access defaults"
        }
      ],
      "close": "The point is not prettier filler. The point is a UI that stays attached to the stack reality underneath it."
    },
    "earlyAccess": {
      "eyebrow": "Current Build State",
      "title": "PicoMUTX is still opening in stages, but the content path is now live.",
      "body": "Pre-registering now gets you into the release loop while the platform is being filled from the builder pack, Academy data, and current repo surfaces rather than placeholder text.",
      "benefits": [
        "Early access to the guided stack map and tutorial flow",
        "Faster feedback loops while the tutor and support surfaces are still sharpening",
        "Visibility into how Hermes, OpenClaw, NanoClaw, and PicoClaw are evolving",
        "A closer line to the product while the content system is still being shaped",
        "First notice when additional surfaces move from placeholder to source-backed"
      ]
    },
    "faq": {
      "eyebrow": "Questions",
      "title": "Questions worth answering honestly",
      "items": [
        {
          "q": "Do I need to code to use PicoMUTX?",
          "a": "You still need to run real commands and verify real runtime state, but Pico is designed to turn that work into a guided operator path instead of an engineer-only maze."
        },
        {
          "q": "How does Pico decide between Hermes, OpenClaw, NanoClaw, and PicoClaw?",
          "a": "It uses fit signals, install realities, troubleshooting themes, and live repo status pulled from the builder pack and current official sources."
        },
        {
          "q": "Does Pico replace the official docs?",
          "a": "No. It compresses them into a product path and keeps links back to the official sources so the stack truth stays inspectable."
        },
        {
          "q": "Why does Tailscale keep showing up across the product?",
          "a": "Because private tailnet access is usually the safer default for dashboards, launchers, and admin surfaces than exposing them directly to the public internet."
        },
        {
          "q": "Will this content keep updating as the repos move?",
          "a": "Yes. The new sync path reads the local pack, optional updated packs, and live repo metadata so the content can be regenerated instead of rewritten by hand."
        }
      ]
    },
    "finalCta": {
      "eyebrow": "Early Access · Live Build",
      "title": "Stop treating stack selection and setup drift like a side quest.",
      "body": "PicoMUTX is being turned into a product surface that names the stacks, tracks the repos, and keeps the operator route visible from first install to safer runtime control.",
      "formHeadline": "Pre-register for PicoMUTX",
      "formSubline": "Join the list while the source-backed build fills in.",
      "ctaButton": "Pre-Register Now",
      "formCtaMeta": "Free to pre-register · No credit card required · Product updates arrive as the live build sharpens"
    }
  },
  "pricing": {
    "pageTitle": "Choose the product depth you actually need",
    "pageSubtitle": "The plans map to real product surfaces: 12 lessons, grounded tutoring, monitored runtime context, and live stack briefs across Hermes, OpenClaw, NanoClaw, and PicoClaw.",
    "pageFooter": "Current content sync tracks 17 pack docs and 4 live repos. Enterprise is for teams that need deeper rollout help, identity controls, and direct support.",
    "planDescriptions": {
      "free": "Inspect the stack map, lesson flow, and product truth before you spend.",
      "starter": "Run one serious build lane with full academy access and grounded tutoring.",
      "pro": "Operate multiple live lanes with BYOK, stronger runtime visibility, and faster escalation.",
      "enterprise": "Roll out across a team with SSO, SLA expectations, and direct operator support."
    },
    "truthStrip": [
      "12 sequenced Academy lessons",
      "17 visible builder-pack docs",
      "4 tracked stack briefings",
      "Private-first remote access defaults"
    ]
  },
  "onboarding": {
    "activationChecklist": [
      {
        "chapter": "01",
        "title": "Install Hermes",
        "body": "Get one clean local Hermes install working end to end."
      },
      {
        "chapter": "02",
        "title": "Run your first agent",
        "body": "Prove the runtime can answer one bounded prompt with the provider you just configured."
      },
      {
        "chapter": "03",
        "title": "Keep proof",
        "body": "Hermes answers one small prompt and the transcript is saved in a file you can reopen."
      }
    ],
    "stackSpotlights": [
      {
        "id": "hermes",
        "name": "Hermes",
        "whyNow": "built-in learning loop",
        "latestSignal": "Release v2026.7.7.2 · Jul 8, 2026"
      },
      {
        "id": "openclaw",
        "name": "OpenClaw",
        "whyNow": "local-first gateway control plane",
        "latestSignal": "Release v2026.7.1 · Jul 13, 2026"
      },
      {
        "id": "nanoclaw",
        "name": "NanoClaw",
        "whyNow": "lightweight mental model",
        "latestSignal": "Release v2.1.17 · Jun 17, 2026"
      },
      {
        "id": "picoclaw",
        "name": "PicoClaw",
        "whyNow": "written in Go",
        "latestSignal": "Release v0.3.1 · Jul 3, 2026"
      }
    ]
  },
  "tutor": {
    "questionProtocol": [
      "Name the exact step, command, or dashboard action you were on.",
      "Paste the evidence: output, error, transcript, or runtime state.",
      "Ask for the one next move that proves the route is live again."
    ],
    "examplePrompts": [
      "Hermes opens locally but the VPS run fails. What should I verify before changing anything?",
      "OpenClaw onboard completed, but the Control UI still does not load. What is the clean verification path?",
      "NanoClaw v2 `nanoclaw.sh` ran, but the container path still feels broken. What should I isolate first?",
      "PicoClaw launcher works on localhost only. Should I change the bind address or keep it private with Tailscale?"
    ]
  },
  "support": {
    "lanes": [
      {
        "id": "fixing-existing",
        "title": "Stack or runtime blocker",
        "body": "Use this when a real install, lesson, dashboard, launcher, or approval step stopped in a way the product cannot close alone."
      },
      {
        "id": "other",
        "title": "Operator walkthrough",
        "body": "Use this when you need a guided session across multiple surfaces instead of one isolated fix."
      }
    ],
    "escalationStandards": [
      {
        "label": "01 • Route",
        "title": "Name the stack and surface",
        "body": "Say whether the problem belongs to Hermes, OpenClaw, NanoClaw, PicoClaw, Tutor, Academy, Autopilot, or the hosted account lane."
      },
      {
        "label": "02 • Evidence",
        "title": "Attach the proof packet",
        "body": "Bring the command, dashboard state, launcher state, or approval signal that shows exactly where the path stopped."
      },
      {
        "label": "03 • Return",
        "title": "Ask for the path back into motion",
        "body": "A good escalation should end with the shortest route back into a lesson, tutor answer, or live control action."
      }
    ]
  },
  "wip": {
    "meta": {
      "title": "Live Build Ledger — PicoMUTX",
      "description": "Inspect the 17 builder-pack docs, tracked repo snapshots, and remote-access defaults now feeding the PicoMUTX experience."
    },
    "title": "Live build ledger",
    "subtitle": "This route no longer exists to apologize for being unfinished. It now shows the source material actively feeding Pico: pack docs, Academy lessons, tracked repos, and the remote-access posture they imply.",
    "overviewTitle": "What is already wired in",
    "overviewBody": "The content path now reads the local builder pack, optional updated pack drops, structured Academy lessons, and live GitHub metadata. This page is the honest place to inspect that feed."
  }
} as const
