"""Generate a verified, stack-specific setup ZIP from onboarding state.

The bundle pins upstream identity and emits only MUTX-owned setup material;
upstream onboarding owns runtime configuration and channel schemas.
"""

from __future__ import annotations

import io
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from src.api.models.pico_onboarding import OnboardingState

KNOWLEDGE_ROOT = Path(__file__).resolve().parents[1] / "knowledge" / "pico-builder-pack"
UPSTREAM_RELEASES = {
    "hermes": {
        "repository": "https://github.com/NousResearch/hermes-agent",
        "ref": "v2026.7.7.2",
        "commit": "9de9c25f620ff7f1ce0fd5457d596052d5159596",
        "version": "0.18.2",
        "runtime": "Python >=3.11,<3.14 (3.12 recommended)",
    },
    "openclaw": {
        "repository": "https://github.com/openclaw/openclaw",
        "ref": "v2026.7.1",
        "commit": "2d2ddc43d0dcf71f31283d780f9fe9ff4cc04fe4",
        "version": "2026.7.1",
        "runtime": "Node >=22.22.3,<23 or >=24.15.0,<25 or >=25.9.0",
    },
    "nanoclaw": {
        "repository": "https://github.com/nanocoai/nanoclaw",
        "ref": "v2.1.17",
        "commit": "ee7f891698760f21b9e79a850d64c7f633cd95ef",
        "version": "2.1.17",
        "runtime": "Node >=20 plus Docker and Claude Code",
    },
    "picoclaw": {
        "repository": "https://github.com/sipeed/picoclaw",
        "ref": "v0.3.1",
        "commit": "2cf030d2fd3b871d7ec17e3be34c24688aac76da",
        "version": "0.3.1",
        "runtime": "Precompiled release binary",
    },
}
COMMON_KB_DOCS = ("INSTALL_FLOW.md", "UPDATE_NOTES.md")
STACK_KB_DOCS = {
    "hermes": "HERMES.md",
    "openclaw": "OPENCLAW.md",
    "nanoclaw": "NANOCLAW.md",
    "picoclaw": "PICOCLAW.md",
}


# ---------------------------------------------------------------------------
# Shared generators
# ---------------------------------------------------------------------------


def _build_env_template(state: OnboardingState) -> str:
    """Provider-secret reference for the upstream onboarding flow."""
    lines = [
        "# Optional provider-secret reference for upstream onboarding",
        "# Do not source this file automatically; each stack has its own credential store.",
        "# Never commit this file or share keys in chat.",
        "",
    ]

    provider_keys = {
        "openai": "OPENAI_API_KEY=sk-...",
        "anthropic": "ANTHROPIC_API_KEY=sk-ant-...",
        "google": "GOOGLE_API_KEY=AIza...",
        "local": "# LOCAL_MODEL_URL=http://127.0.0.1:1234/v1",
    }

    if state.provider:
        lines.append(provider_keys.get(state.provider, "# PROVIDER_KEY="))
    else:
        for v in provider_keys.values():
            lines.append(v)

    lines.append("")
    if state.channels:
        if "telegram" in state.channels:
            lines.append("TELEGRAM_BOT_TOKEN=")
        if "discord" in state.channels:
            lines.append("DISCORD_BOT_TOKEN=")
        if "slack" in state.channels:
            lines.append("SLACK_BOT_TOKEN=")
            lines.append("SLACK_SIGNING_SECRET=")
        if "whatsapp" in state.channels:
            lines.append("WHATSAPP_TOKEN=")

    return "\n".join(lines)


def _build_upstream_lock(state: OnboardingState) -> str:
    """Record the exact upstream identity used by the generated package."""
    import json

    stack = state.stack or "hermes"
    release = UPSTREAM_RELEASES[stack]
    return (
        json.dumps(
            {
                "schema_version": 1,
                "stack": stack,
                "repository": release["repository"],
                "ref": release["ref"],
                "commit": release["commit"],
                "version": release["version"],
                "runtime": release["runtime"],
                "verified_at": "2026-07-16",
            },
            indent=2,
        )
        + "\n"
    )


def _build_agents_md(state: OnboardingState) -> str:
    """Hermes AGENTS.md template."""
    stack_name = (state.stack or "hermes").title()
    return f"""# {stack_name} Agent Configuration

> Generated by PicoMUTX Builder

## Context
- Stack: {state.stack or "not set"}
- OS: {state.os or "not set"}
- Provider: {state.provider or "not set"}
- Goal: {state.goal or "not set"}

## Instructions
This agent helps with tasks defined by the operator.
Customize the skills and toolsets in config.yaml as needed.
"""


def _build_install_sh(state: OnboardingState) -> str:
    """Build a release-pinned installer without mutable remote shell execution."""
    os_name = state.os or "linux"
    stack = state.stack or "hermes"

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "echo '=== PicoMUTX verified setup ==='",
        "echo 'This installer uses the exact upstream release recorded in upstream.lock.json.'",
        "",
    ]

    if stack == "hermes":
        lines += [
            "HERMES_REF='v2026.7.7.2'",
            "HERMES_COMMIT='9de9c25f620ff7f1ce0fd5457d596052d5159596'",
            'HERMES_DIR="${HERMES_HOME:-$HOME/.hermes}/hermes-agent"',
            "command -v git >/dev/null || { echo 'git is required'; exit 1; }",
            "command -v uv >/dev/null || { echo 'uv is required: https://docs.astral.sh/uv/'; exit 1; }",
            'if [ -e "$HERMES_DIR" ]; then',
            '  echo "Refusing to overwrite existing Hermes directory: $HERMES_DIR"',
            "  exit 1",
            "fi",
            'git clone --branch "$HERMES_REF" --depth 1 https://github.com/NousResearch/hermes-agent.git "$HERMES_DIR"',
            'cd "$HERMES_DIR"',
            '[ "$(git rev-parse HEAD)" = "$HERMES_COMMIT" ] || { echo "Hermes tag did not resolve to the audited commit"; exit 1; }',
            "uv sync --extra all --python 3.12",
            "uv run hermes setup",
        ]
    elif stack == "openclaw":
        lines += [
            "OPENCLAW_VERSION='2026.7.1'",
            "OPENCLAW_INSTALL_COMMIT='2d2ddc43d0dcf71f31283d780f9fe9ff4cc04fe4'",
            "command -v curl >/dev/null || { echo 'curl is required'; exit 1; }",
            'curl -fsSL --proto \'=https\' --tlsv1.2 "https://raw.githubusercontent.com/openclaw/openclaw/$OPENCLAW_INSTALL_COMMIT/scripts/install.sh" | bash -s -- --install-method npm --version "$OPENCLAW_VERSION"',
        ]
    elif stack == "nanoclaw":
        lines += [
            "NANOCLAW_REF='v2.1.17'",
            "NANOCLAW_COMMIT='ee7f891698760f21b9e79a850d64c7f633cd95ef'",
            "command -v git >/dev/null || { echo 'git is required'; exit 1; }",
            "command -v docker >/dev/null || { echo 'Docker is required'; exit 1; }",
            "docker info >/dev/null 2>&1 || { echo 'Docker must be running'; exit 1; }",
            "[ ! -e nanoclaw-v2 ] || { echo 'Refusing to overwrite ./nanoclaw-v2'; exit 1; }",
            'git clone --branch "$NANOCLAW_REF" --depth 1 https://github.com/nanocoai/nanoclaw.git nanoclaw-v2',
            "cd nanoclaw-v2",
            '[ "$(git rev-parse HEAD)" = "$NANOCLAW_COMMIT" ] || { echo "NanoClaw tag did not resolve to the audited commit"; exit 1; }',
            "bash nanoclaw.sh",
        ]
    elif stack == "picoclaw":
        if os_name == "android":
            lines += [
                "echo 'Use the signed v0.3.1 Android package from:'",
                "echo 'https://github.com/sipeed/picoclaw/releases/download/v0.3.1/picoclaw-android-universal.zip'",
                "echo 'Verify it against picoclaw_0.3.1_checksums.txt before installing.'",
            ]
        else:
            platform = "Darwin" if os_name == "macos" else "Linux"
            lines += [
                "PICOCLAW_VERSION='0.3.1'",
                f"PICOCLAW_PLATFORM='{platform}'",
                'case "$(uname -m)" in',
                "  x86_64|amd64) PICOCLAW_ARCH='x86_64' ;;",
                "  arm64|aarch64) PICOCLAW_ARCH='arm64' ;;",
                '  *) echo "Unsupported architecture: $(uname -m)"; exit 1 ;;',
                "esac",
                'ASSET="picoclaw_${PICOCLAW_PLATFORM}_${PICOCLAW_ARCH}.tar.gz"',
                'BASE="https://github.com/sipeed/picoclaw/releases/download/v${PICOCLAW_VERSION}"',
                'TMP_DIR="$(mktemp -d)"',
                "trap 'rm -rf \"$TMP_DIR\"' EXIT",
                'curl --fail --location --proto "=https" --tlsv1.2 -o "$TMP_DIR/$ASSET" "$BASE/$ASSET"',
                'curl --fail --location --proto "=https" --tlsv1.2 -o "$TMP_DIR/checksums.txt" "$BASE/picoclaw_${PICOCLAW_VERSION}_checksums.txt"',
                '(cd "$TMP_DIR" && grep "  $ASSET$" checksums.txt > selected-checksum.txt)',
                'if command -v sha256sum >/dev/null; then (cd "$TMP_DIR" && sha256sum -c selected-checksum.txt); else (cd "$TMP_DIR" && shasum -a 256 -c selected-checksum.txt); fi',
                'tar -xzf "$TMP_DIR/$ASSET" -C "$TMP_DIR"',
                'mkdir -p "$HOME/.local/bin"',
                'install -m 0755 "$TMP_DIR/picoclaw" "$HOME/.local/bin/picoclaw"',
                '"$HOME/.local/bin/picoclaw" onboard',
            ]

    lines.append("")
    lines.append("echo 'Setup complete. Check README.md for next steps.'")

    return "\n".join(lines)


def _build_tailscale_setup(state: OnboardingState) -> str:
    """Tailscale setup script — included only when networking == tailscale."""
    return """#!/usr/bin/env bash
set -euo pipefail

echo '=== Tailscale Setup ==='

command -v tailscale >/dev/null || {
  echo 'Install Tailscale from https://tailscale.com/download, then rerun this script.'
  exit 1
}

echo 'Authenticating with Tailscale...'
sudo tailscale up

echo 'Tailscale is active.'
echo '  Status: tailscale status'
echo '  Your IP: tailscale ip'
echo ''
echo 'To share a local service on your tailnet:'
echo '  tailscale serve --bg <port>'
echo ''
echo 'WARNING: tailscale funnel exposes services publicly. Do NOT use unless needed.'
"""


def _builder_docs_for_state(state: OnboardingState) -> list[tuple[str, str]]:
    """Return builder-pack docs that should ship inside the ZIP."""
    stack = state.stack or "hermes"
    doc_names = list(COMMON_KB_DOCS)

    stack_doc = STACK_KB_DOCS.get(stack)
    if stack_doc:
        doc_names.append(stack_doc)

    if state.networking == "tailscale":
        doc_names.append("TAILSCALE_PLAYBOOK.md")

    docs: list[tuple[str, str]] = []
    for name in doc_names:
        docs.append((f"kb/{name}", (KNOWLEDGE_ROOT / name).read_text("utf-8")))

    return docs


def _build_readme(state: OnboardingState) -> str:
    """The key deliverable — personalized install guide."""
    stack = state.stack or "hermes"
    os_name = state.os or "linux"
    provider = state.provider or "openai"

    stack_names = {
        "hermes": "Hermes",
        "openclaw": "OpenClaw",
        "nanoclaw": "NanoClaw",
        "picoclaw": "PicoClaw",
    }
    os_names = {
        "macos": "macOS",
        "linux": "Linux",
        "windows_wsl2": "Windows (WSL2)",
        "android": "Android",
    }
    provider_names = {
        "openai": "OpenAI",
        "anthropic": "Anthropic",
        "google": "Google",
        "local": "Local (LM Studio/Ollama)",
    }

    s = stack_names.get(stack, stack.title())
    o = os_names.get(os_name, os_name.title())
    p = provider_names.get(provider, provider.title())

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        f"# {s} Setup Guide",
        "",
        f"> Generated by PicoMUTX Builder on {now}",
        f"> Stack: **{s}** | OS: **{o}** | Provider: **{p}**",
        "",
        "## Quick Start",
        "",
        "### 1. Review the upstream lock",
        "",
        "`upstream.lock.json` records the exact repository, release ref, and runtime used by this package.",
        "Do not replace its pinned ref with `main`, `latest`, or an unverified installer URL.",
        "",
        "`.env.template` is only a secret-name reference. The upstream onboarding flow remains the authority for credential storage.",
        "",
    ]

    if state.channels:
        ch_list = ", ".join(state.channels)
        lines += [
            "### 2. Note the requested channels",
            "",
            f"Channels selected: **{ch_list}**",
            "",
            "Configure these through the selected stack's current onboarding flow.",
            "PicoMUTX intentionally does not emit guessed cross-stack YAML schemas.",
            "",
        ]

    install_step = 3 if state.channels else 2
    verify_step = install_step + 1
    lines += [
        f"### {install_step}. Run the install script",
        "",
        "```bash",
        "chmod +x install.sh",
        "./install.sh",
        "```",
        "",
        f"### {verify_step}. Verify",
        "",
    ]

    verify_cmds = {
        "hermes": 'cd "${HERMES_HOME:-$HOME/.hermes}/hermes-agent" && uv run hermes doctor',
        "openclaw": "openclaw --version && openclaw gateway status",
        "nanoclaw": "cd nanoclaw-v2 && docker ps",
        "picoclaw": "picoclaw --version && picoclaw status",
    }
    lines.append(f"```bash\n{verify_cmds.get(stack, 'echo check-your-setup')}\n```")

    lines += [
        "",
        "## Troubleshooting",
        "",
        "- If the install fails, check the error output carefully",
        "- Ensure your API key is valid and has credits",
        "- For networking issues, check that ports are not in use",
        "",
        "## Included Builder KB",
        "",
        "- `kb/INSTALL_FLOW.md` — current install order and verification rules used by the builder",
        f"- `kb/{STACK_KB_DOCS.get(stack, 'HERMES.md')}` — current stack-specific notes from the builder pack",
        "- `kb/UPDATE_NOTES.md` — what changed in the refreshed builder knowledge base",
        "",
        "## Need Help?",
        "",
        "Come back to **pico.mutx.dev** — your session is saved.",
        "",
        "## Security Reminder",
        "",
        "- Never share your `.env` file",
        "- Never paste API keys in chat",
        "- Keep your agent dashboard on localhost or behind Tailscale",
    ]

    if state.networking == "tailscale":
        lines += [
            "",
            "- `kb/TAILSCALE_PLAYBOOK.md` — current remote-access guidance for Tailscale",
            "",
            "## Tailscale Setup",
            "",
            "A `tailscale-setup.sh` script is included. Run it to set up private remote access.",
            "",
            "```bash",
            "chmod +x tailscale-setup.sh",
            "./tailscale-setup.sh",
            "```",
        ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def build_onboarding_package(state: OnboardingState) -> tuple[bytes, str]:
    """Generate a verified ZIP without inventing upstream runtime config.

    Returns:
        (zip_bytes, filename) — filename is '{stack}-setup.zip'
    """
    stack = state.stack or "hermes"
    filename = f"{stack}-setup.zip"

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Only emit files whose format MUTX owns. Upstream onboarding owns runtime config.
        if stack == "hermes":
            zf.writestr("AGENTS.md", _build_agents_md(state))

        # Shared files
        zf.writestr("upstream.lock.json", _build_upstream_lock(state))
        zf.writestr(".env.template", _build_env_template(state))
        zf.writestr("install.sh", _build_install_sh(state))
        zf.writestr("README.md", _build_readme(state))
        for archive_name, content in _builder_docs_for_state(state):
            zf.writestr(archive_name, content)

        # Tailscale
        if state.networking == "tailscale":
            zf.writestr("tailscale-setup.sh", _build_tailscale_setup(state))

    return buf.getvalue(), filename
