{{- if .Values.otelCollector.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mutx.fullname" . }}-otel-collector
  labels:
    {{- include "mutx-otel-collector.labels" . | nindent 4 }}
  {{- with .Values.otelCollector.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.otelCollector.service.type }}
  ports:
    - name: otlp-grpc
      port: {{ .Values.otelCollector.service.ports.otlpGrpc }}
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.otelCollector.service.ports.otlpHttp }}
      targetPort: otlp-http
      protocol: TCP
    - name: zipkin
      port: {{ .Values.otelCollector.service.ports.zipkin }}
      targetPort: zipkin
      protocol: TCP
    - name: metrics
      port: {{ .Values.otelCollector.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
    - name: prom-exp
      port: {{ .Values.otelCollector.service.ports.prometheusExporter }}
      targetPort: prom-exp
      protocol: TCP
  selector:
    {{- include "mutx-otel-collector.selectorLabels" . | nindent 4 }}
{{- end }}
